name: auto-release

on:
  push:
    tags:
      - '*-SNAPSHOT'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/libs/*-all.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
